# Generated by Django 4.0.6 on 2022-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя тэга')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет тэга')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug тэга')),
            ],
            options={
                'verbose_name': 'тэг',
                'verbose_name_plural': 'тэги',
            },
        ),
    ]
